extends: stylelint-config-htmlacademy

rules:
  declaration-no-important: true
  indentation:
    - tab
    - ignore: [inside-parens ]
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - mixin
      - define-mixin
      - include
      - content
      - rules
      - each
      - use
